### ISSUE TITLE
please fix homepage link on https://pypi.org/project/fedora-messaging-the-new-hotness-schema/

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/the-new-hotness-messages#9]
please fix homepage link on
https://pypi.org/project/fedora-messaging-the-new-hotness-schema/

the correct homepage is
https://github.com/fedora-infra/the-new-hotness-messages

and is not https://github.com/fedora-infra/the-new-hotness 

Thank you

**Comment by Zlopez** [comment]
This will be fixed in next release
